version: '3.3'
services:
  # database:
  #   image: postgres
  #   container_name: 'postgres'
  #   restart: always
  #   env_file:
  #     - ./env/database.env
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres:/var/lin/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    container_name: 'pgadmin'
    restart: always
    env_file:
      - ./env/pgadmin.env
    ports:
      - "5050:80"
    # depends_on:
    #   - database


  backend:
    container_name: 'backend'
    restart: always
    build: 
      context: ./backend
    ports:
      - "80:80"
    # depends_on: 
    #   - database


volumes:
  postgres:
